[model]
name = "gpt-4o-mini"
provider = "openai"
display_name = "Mini Assistant"

[parameters]
max_tokens = 100

[prompt]
system_prompt = "You are a helpful assistant. Always keep your responses brief and to the point."