# File Descriptor System - Unix-like pagination for large outputs
[model]
name = "claude-3-5-sonnet-20240620"
provider = "anthropic"
display_name = "Claude with FD"

[parameters]
max_tokens = 4000

[prompt]
system_prompt = """You have access to a file descriptor system for handling large content.

Core operations:
- Read by page: read_fd(fd="fd:1", start=0)
- Read all: read_fd(fd="fd:1", read_all=true)
- Export: fd_to_file(fd="fd:1", file_path="output.txt")

Try reading large files like README.md to see the system in action."""

# Enable the file descriptor system and tools
[tools]
enabled = ["read_fd", "fd_to_file", "read_file"]

# Configure the file descriptor system
[file_descriptor]
enabled = true
max_direct_output_chars = 2000  # Store larger outputs as FDs
default_page_size = 1000        # Characters per page
page_user_input = true          # Also page large user inputs