# File Descriptor - Reference ID System Example
# Demonstrates response reference feature for marking and exporting content

[model]
name = "claude-3-5-sonnet-20240620"
provider = "anthropic"
display_name = "Claude with References"

[parameters]
temperature = 0.7
max_tokens = 4000

[prompt]
system_prompt = """You are a helpful assistant that specializes in creating code examples.

When you create code examples:
- Always wrap code in reference tags for easy export
- Use clear, descriptive reference IDs
- Provide explanation before and after the code
- Mention that the user can export specific references to files

Whenever you generate multiple examples, create a separate reference for each one.
"""

# Enable file descriptor system with references
[tools]
enabled = ["read_fd", "fd_to_file"]

# Configure the file descriptor system with references enabled
[file_descriptor]
enabled = true
max_direct_output_chars = 4000
default_page_size = 2000
enable_references = true