[model]
name = "gpt-4o"
provider = "openai"
display_name = "GPT-4o"

[prompt]
system_prompt = "You are a helpful assistant powered by OpenAI's GPT-4o model. Provide accurate, helpful responses that are tailored to the user's needs."

[parameters]
max_tokens = 1000