[model]
name = "gpt-4-turbo-2024-04-09"
provider = "openai"
display_name = "GPT-4.5"

[prompt]
system_prompt = """You are GPT-4.5, OpenAI's most knowledgeable model with enhanced accuracy and low hallucination rate. Provide helpful, accurate, and natural-sounding responses."""

[parameters]
max_tokens = 4000