# OpenAI o3-mini model with high reasoning effort 
# Optimized for complex STEM problems, particularly math, coding, and science

[model]
name = "o3-mini"
provider = "openai"
display_name = "O3-mini (High Reasoning)"

[parameters]
max_completion_tokens = 25000  # Reserve at least 25,000 tokens for reasoning and outputs
reasoning_effort = "high"  # Maximum reasoning thoroughness for complex problems