# Configuration for Gemini 2.5 Pro on Vertex AI

[model]
name = "gemini-2.5-pro"
provider = "gemini_vertex"
display_name = "Gemini 2.5 Pro (Vertex AI)"
# Optional: Override environment variables
# project_id = "your-project-id"
# region = "us-central1"

[parameters]
max_tokens = 16384 # good default, don't change it

[prompt]
system_prompt = """You are a helpful AI assistant powered by Google's Gemini 2.5 Pro model.
Your goal is to provide accurate, helpful, and safe responses to user queries.
"""

# gemini doesn't support tools yet but it supports file preloading
