# Configuration for Gemini 2.0 Flash (Direct API)

[model]
name = "gemini-2.0-flash"
provider = "gemini"
display_name = "Gemini 2.0 Flash (Direct API)"

[parameters]
temperature = 0.7
max_tokens = 4096

[prompt]
system_prompt = """You are a helpful AI assistant powered by Google's Gemini 2.0 Flash model.
Your goal is to provide accurate, helpful, and safe responses to user queries.
"""