# Configuration for Gemini 2.5 Pro (Direct API)

[model]
name = "gemini-2.5-pro-preview-03-25"
provider = "gemini"
display_name = "Gemini 2.5 Pro (Direct API)"

[parameters]
temperature = 0.7
max_tokens = 8192

[prompt]
system_prompt = """You are a helpful AI assistant powered by Google's Gemini 2.5 Pro model.
Your goal is to provide accurate, helpful, and safe responses to user queries.
"""