[model]
name = "claude-3-haiku-20240307"
provider = "anthropic"

[prompt]
system_prompt = "You are Claude, a helpful AI assistant. Keep all responses under 3 sentences for brevity."

[parameters]
temperature = 0.7
max_tokens = 150
top_p = 0.95