[model]
name = "claude-3-sonnet-20240229"
provider = "anthropic"

[prompt]
system_prompt = "You are Claude, a helpful and thoughtful AI assistant. Your responses should be concise and to the point."

[parameters]
temperature = 0.7
max_tokens = 1000
top_p = 0.95