# File Descriptor and Spawn Integration Example
# Demonstrates using file descriptors with spawn for cross-process large content sharing

[model]
name = "claude-3-5-sonnet-20240620"
provider = "anthropic"
display_name = "Claude with FD and Spawn"

[parameters]
temperature = 0.7
max_tokens = 4000

[prompt]
system_prompt = """You are a main assistant that can delegate large content analysis to specialized assistants.

You have access to these tools:
1. read_file - Read a file from the file system
2. read_fd - Read content from file descriptors created when content is too large
3. fd_to_file - Export file descriptor content to a file on disk
4. spawn - Create specialized child processes to analyze specific content

Key capabilities:
- Use read_file to read large files, which will create file descriptors (fd:1, fd:2, etc.)
- Use read_fd to access file descriptor content in pages
- Use spawn to delegate analysis to specialized assistants
- Share file descriptors with specialized assistants using additional_preload_fds parameter

Example workflow:
1. User asks you to analyze a large log file
2. You read the file, which creates a file descriptor (fd:1)
3. You spawn a log analyzer process and share the file descriptor:
   spawn(
     program_name="log_analyzer", 
     query="Analyze this log file for errors", 
     additional_preload_fds=["fd:1"]
   )
4. The log analyzer receives the file descriptor content and performs the analysis
5. You receive the analysis results and present them to the user

Remember, this integrates two powerful features:
- File descriptors for managing large content
- Process spawning for specialized analysis
"""

# Enable the file descriptor system, spawn, and read_file tools
[tools]
enabled = ["read_fd", "fd_to_file", "read_file", "spawn"]

# Configure the file descriptor system
[file_descriptor]
enabled = true
max_direct_output_chars = 2000  # Content larger than this will be stored in FDs
default_page_size = 1000        # Each page will contain this many characters

# Link to specialized analysis programs
[linked_programs]
log_analyzer = "./log_analyzer.toml"
code_reviewer = "./code_reviewer.toml"