[model]
name = "claude-3-haiku-20240307"
provider = "anthropic"
display_name = "Claude Time Assistant"

[parameters]
temperature = 0.7
max_tokens = 300

[prompt]
system_prompt = """You are a helpful assistant with access to tools. 
You can use the time.current tool to get the current time.
Always use the tool when asked about the current time instead of guessing.
"""

[mcp]
config_path = "../config/mcp_servers.json"

[mcp.tools]
# Only use time server for a more reliable example
time = ["current"]