[model]
name = "claude-3-5-haiku-20241022"
provider = "anthropic"
display_name = "Claude MCP Assistant"

[parameters]
temperature = 0.7
max_tokens = 1000

[prompt]
system_prompt = """You are a helpful assistant with access to tools.
When you need to perform specific tasks or look up information, use the appropriate tool.
Be concise and clear in your responses.
"""

[mcp]
config_path = "/Users/ttj/github/agent-process/llmproc/worktrees/mcp/config/mcp_servers.json"

[mcp.tools]
# Using 'all' to capture any tools available from any servers
unknown = "all" 
