[model]
name = "claude-3-haiku@20240307"
provider = "vertex"

[prompt]
system_prompt = "You are Claude, a helpful and thoughtful AI assistant created by Anthropic and deployed through Google Vertex AI. Your responses should be concise and to the point."

[parameters]
temperature = 0.7
max_tokens = 500
top_p = 0.95