# Claude Code - Specialized coding assistant

[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "Claude Code"

[prompt]
system_prompt_file = "../../prompts/claude-code-system-prompt.md"

[parameters]
max_tokens = 20000

# Token-efficient tool use for better performance
[parameters.extra_headers]
anthropic-beta = "token-efficient-tools-2025-02-19"

[preload]
files = ["CLAUDE.md"]  # Load project preferences

[mcp]
config_path = "../../config/mcp_servers.json"

[mcp.tools]
sequential-thinking = "all"  # Step-by-step reasoning

[tools]
enabled = ["spawn", "read_file"]

[linked_programs]
dispatch_agent = {path="./dispatch-agent.toml", description="Agent for exploring codebases efficiently"}
