[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "Claude Code"

[prompt]
system_prompt_file = "../../prompts/claude-code-system-prompt.md"

[parameters]
temperature = 1
max_tokens = 20000

# Enable token-efficient tool use for reduced token usage and lower latency
[parameters.extra_headers]
anthropic-beta = "token-efficient-tools-2025-02-19"

# Enable high thinking capacity for complex coding tasks
#[parameters.thinking]
#type = "disabled"
#budget_tokens = 16000

[preload]
files = ["CLAUDE.md"]

[mcp]
config_path = "../../config/mcp_servers.json"

[mcp.tools]
# Use the sequential-thinking tool which provides reasoning capabilities
sequential-thinking = "all"

[tools]
enabled = ["spawn", "read_file"]


[linked_programs]
dispatch_agent = { path = "./dispatch-agent.toml", description = "Specialized agent for searching and exploring codebases efficiently" }
