[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "Claude Code Dispatch Agent"

[prompt]
system_prompt_file = "../../prompts/claude-code-dispatch-agent-system-prompt.md"

[parameters]
temperature = 1
max_tokens = 20000

# Enable token-efficient tool use for reduced token usage and lower latency
[parameters.extra_headers]
anthropic-beta = "token-efficient-tools-2025-02-19"

# Enable medium thinking capacity for balanced search performance
[parameters.thinking]
type = "enabled"
budget_tokens = 4000

[mcp]
config_path = "../../config/mcp_servers.json"

[mcp.tools]
# this is the full list of tools
#codemcp = ["read_file", "write_file", "edit_file", "ls", "grep", "init_project_tool"]
# we only allow read only access to the file system for demo purposes
codemcp = ["read_file", "ls", "grep"]
