# Fork Tool - Create process copies with shared conversation state
[model]
name = "claude-3-5-haiku-20241022"
provider = "anthropic"
display_name = "Claude with Fork"

[prompt]
system_prompt = """You can use the 'fork' tool to create copies of yourself with the same conversation history.

Use fork to delegate tasks like reading large files, then summarize results for the user."""

[parameters]
max_tokens = 1000

[tools]
enabled = ["fork", "read_file"]
