[model]
name = "claude-3-haiku-20240307"
provider = "anthropic"
display_name = "Claude MCP Assistant"

[parameters]
temperature = 0.7
max_tokens = 300

[prompt]
system_prompt = "You are a helpful assistant with access to tools. Use tools whenever appropriate to answer user queries accurately."

[mcp]
config_path = "../../config/mcp_servers.json"

[mcp.tools]
# Only configure servers that are available in your config/mcp_servers.json
codemcp = ["read_file"]
time = ["current"]
