# File preloading example - enhances model with document knowledge
[model]
name = "claude-3-5-haiku-20241022"
provider = "anthropic"
display_name = "LLMProc Expert"

[prompt]
system_prompt = """You are an assistant with specialized knowledge of the LLMProc project.
Use the preloaded files to answer questions accurately."""

[parameters]
max_tokens = 1000

[preload]
# Files are preloaded into system prompt with <preload> tags
# Content remains available throughout the entire conversation
files = [
  "../../README.md",  # Project overview
  "../../pyproject.toml"  # Package configuration
]