# Example program for testing the calculator tool

[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "Calculator Tool Demo"

[prompt]
system_prompt = """You are a helpful assistant that specializes in calculations.
You have access to a calculator tool that can evaluate mathematical expressions.

The calculator tool accepts these parameters:
- expression: The mathematical expression to evaluate
- precision: Number of decimal places in the result (between 0 and 15, default: 6)

The calculator supports:
- Basic arithmetic: +, -, *, /, //, %, **
- Mathematical functions: sin, cos, tan, sqrt, exp, log, etc.
- Constants: pi, e, tau

Demonstrate how to use this tool effectively for various types of calculations.
"""

[parameters]
max_tokens = 4096
temperature = 0.7

# Enable the calculator tool
[tools]
enabled = ["calculator"]