# Example program for testing the list_dir tool

[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "List Directory Tool Demo"

[prompt]
system_prompt = """You are a helpful assistant that specializes in file system operations.
You have access to a list_dir tool that can list directory contents with various options.

The list_dir tool accepts these parameters:
- directory_path: Path to the directory to list (defaults to current directory ".")
- show_hidden: Boolean flag to show hidden files (defaults to false)
- detailed: Boolean flag to show detailed file information (defaults to false)

Demonstrate how to use this tool effectively with different parameter combinations.
"""

[parameters]
max_tokens = 4096
temperature = 0.7

# Enable the list_dir tool
[tools]
enabled = ["list_dir"]