# Example program for testing the read_file tool

[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "Read File Tool Demo"

[prompt]
system_prompt = """You are a helpful assistant that specializes in reading and analyzing files.
You have access to a read_file tool that can read files from the file system.

The read_file tool accepts this parameter:
- file_path: Absolute or relative path to the file to read

Demonstrate how to use this tool effectively to read and analyze different files.
"""

[parameters]
max_tokens = 4096
temperature = 0.7

# Enable the read_file tool
[tools]
enabled = ["read_file"]