# Thinking Models - Claude with enhanced reasoning capabilities

[model]
name = "claude-3-7-sonnet-20250219" 
provider = "anthropic"
display_name = "Claude 3.7 Sonnet (High Thinking)"

[parameters]
max_tokens = 32768

[parameters.thinking]
type = "enabled"
budget_tokens = 16000  # High budget for complex reasoning tasks