# Claude 3.7 Sonnet model with medium thinking budget
# Balanced for general-purpose reasoning with good performance and latency

[model]
name = "claude-3-7-sonnet-20250219" 
provider = "anthropic"
display_name = "Claude 3.7 Sonnet (Medium Thinking)"

[parameters]
max_tokens = 16384  # Set to a consistent value that works well without streaming

[parameters.thinking]
type = "enabled"
budget_tokens = 4000  # Medium thinking budget for balanced performance