# Thinking Models - Claude with enhanced reasoning capabilities

[model]
name = "claude-3-7-sonnet-20250219" 
provider = "anthropic"
display_name = "Claude 3.7 Sonnet (High Thinking)"

[parameters]
max_tokens = 16384  # Set to a consistent value that works well without streaming

[parameters.thinking]
type = "enabled"
budget_tokens = 8000  # Reduced from 16000 to avoid timeout issues, still high enough for complex reasoning