[model]
name = "claude-3-7-sonnet-20250219"
provider = "anthropic"
display_name = "Claude 3.7 Sonnet"
# disable_automatic_caching = false  # Uncomment to disable automatic caching

[prompt]
system_prompt = """You are Claude 3.7 Sonnet, Anthropic's most intelligent AI assistant with extended thinking capabilities. Provide thoughtful, accurate responses with the option to use deeper reasoning when needed for complex problems."""

[parameters]
max_tokens = 4096
# Prompt caching is automatically enabled