[model]
name = "claude-3-5-haiku@20241022"  # Use appropriate Vertex model name
provider = "anthropic_vertex"
display_name = "Claude Haiku (Vertex AI)"

[prompt]
system_prompt = "You are Claude on Vertex AI, a helpful AI assistant. Keep all responses under 3 sentences for brevity."

[parameters]
max_tokens = 150

# These are used for Vertex AI authentication
# Will be loaded from environment variables if not specified
# project_id = "your-gcp-project-id"  # Can also use ANTHROPIC_VERTEX_PROJECT_ID env var
# region = "us-central1"  # Can also use CLOUD_ML_REGION env var (defaults to us-central1)