# Claude 3.7 Sonnet model with high thinking budget
# Optimized for complex STEM problems, particularly math, coding, and scientific analysis

[model]
name = "claude-3-7-sonnet-20250219" 
provider = "anthropic"
display_name = "Claude 3.7 Sonnet (High Thinking)"

[parameters]
max_tokens = 32768  # Reserve sufficient tokens for thinking and outputs

[parameters.thinking]
type = "enabled"
budget_tokens = 16000  # High thinking budget for complex problems