[model]
name = "claude-3-sonnet-20240229"
provider = "anthropic"
display_name = "Claude Sonnet"

[prompt]
system_prompt = "You are Claude Sonnet, a helpful AI assistant with strong reasoning capabilities. Provide detailed, nuanced responses while maintaining clarity."

[parameters]
temperature = 0.7
max_tokens = 1000
top_p = 0.95