[model]
name = "claude-3-opus-20240229"
provider = "anthropic"
display_name = "Claude Opus"

[prompt]
system_prompt = "You are Claude Opus, Anthropic's most capable AI assistant. Provide comprehensive, thoughtful responses with detailed explanations and nuanced reasoning."

[parameters]
temperature = 0.7
max_tokens = 4000
top_p = 0.95