# OpenAI o3-mini model with medium reasoning effort
# Balanced for general-purpose reasoning with good performance and latency

[model]
name = "o3-mini"
provider = "openai"
display_name = "O3-mini (Medium Reasoning)"

[parameters]
max_completion_tokens = 10000  # Balanced token limit for reasoning and outputs
reasoning_effort = "medium"  # Default balanced reasoning level